db_schema_str = """
CREATE TABLE customers (
    customer_id SERIAL PRIMARY KEY,
    customer_name VARCHAR(64)
);

CREATE TABLE countries (
    country_id SERIAL PRIMARY KEY,
    country_name VARCHAR(64)
);

CREATE TABLE locations (
    location_id SERIAL PRIMARY KEY,
    location_name VARCHAR(64),
    country_id INT REFERENCES countries(country_id)
);

CREATE TABLE sales (
    sale_id SERIAL PRIMARY KEY,
    order_date DATE,
    price_paid NUMERIC(10, 2),
    customer_id INT REFERENCES customers(customer_id),
    location_id INT REFERENCES locations(location_id)
);
"""

seed_values_str = """
INSERT INTO countries
(country_name)
VALUES
('Antigua'),
('Argentina'),
('Cambodia'),
('Canada'),
('Chile'),
('Colombia'),
('Costa Rica'),
('Dominica'),
('England'),
('Fiji'),
('France'),
('Greece'),
('India'),
('Indonesia'),
('Italy'),
('Japan'),
('Maldives'),
('Mexico'),
('Morocco'),
('Nicaragua'),
('Peru'),
('Rwanda'),
('Saint Vincent and the Grenadines'),
('Singapore'),
('South Africa'),
('Spain'),
('St. Lucia'),
('Tanzania'),
('Thailand'),
('Turkey'),
('Turks and Caicos Islands'),
('United States'),
('Vietnam');

INSERT INTO locations
(location_name, country_id)
VALUES
('Hotel',
(SELECT country_id FROM countries WHERE country_name = 'Country')),
('Rosewood Castiglion del Bosco',
(SELECT country_id FROM countries WHERE country_name = 'Italy')),
('Grace Hotel',
(SELECT country_id FROM countries WHERE country_name = 'Greece')),
('Waldorf Astoria Maldives Ithaafushi',
(SELECT country_id FROM countries WHERE country_name = 'Maldives')),
('Pickering House Inn',
(SELECT country_id FROM countries WHERE country_name = 'United States')),
('One&Only Reethi Rah',
(SELECT country_id FROM countries WHERE country_name = 'Maldives')),
('Royal Mansour Marrakech',
(SELECT country_id FROM countries WHERE country_name = 'Morocco')),
('Capella Ubud',
(SELECT country_id FROM countries WHERE country_name = 'Indonesia')),
('The Lowell',
(SELECT country_id FROM countries WHERE country_name = 'United States')),
('H�tel Madame R�ve',
(SELECT country_id FROM countries WHERE country_name = 'France')),
('Rosewood Villa Magna',
(SELECT country_id FROM countries WHERE country_name = 'Spain')),
('The Oberoi New Delhi',
(SELECT country_id FROM countries WHERE country_name = 'India')),
('The Oberoi Udaivilas',
(SELECT country_id FROM countries WHERE country_name = 'India')),
('Mandapa,a Ritz-Carlton Reserve',
(SELECT country_id FROM countries WHERE country_name = 'Indonesia')),
('Wilderness Safaris Bisate Lodge',
(SELECT country_id FROM countries WHERE country_name = 'Rwanda')),
('Portrait Firenze',
(SELECT country_id FROM countries WHERE country_name = 'Italy')),
('Raffles Istanbul',
(SELECT country_id FROM countries WHERE country_name = 'Turkey')),
('The Oberoi Marrakech',
(SELECT country_id FROM countries WHERE country_name = 'Morocco')),
('Capella Hanoi',
(SELECT country_id FROM countries WHERE country_name = 'Vietnam')),
('White Elephant Palm Beach',
(SELECT country_id FROM countries WHERE country_name = 'United States')),
('The Loutrel',
(SELECT country_id FROM countries WHERE country_name = 'United States')),
('Monasterio',
(SELECT country_id FROM countries WHERE country_name = 'Peru')),
('Sani Asterias',
(SELECT country_id FROM countries WHERE country_name = 'Greece')),
('Shangri-La the Shard',
(SELECT country_id FROM countries WHERE country_name = 'England')),
('Coquillade Provence Resort & Spa',
(SELECT country_id FROM countries WHERE country_name = 'France')),
('Taj Palace',
(SELECT country_id FROM countries WHERE country_name = 'India')),
('Pendry Chicago',
(SELECT country_id FROM countries WHERE country_name = 'United States')),
('Nayara Tented Camp',
(SELECT country_id FROM countries WHERE country_name = 'Costa Rica')),
('Hotel Belmar',
(SELECT country_id FROM countries WHERE country_name = 'Costa Rica')),
('Royal Champagne H�tel & Spa',
(SELECT country_id FROM countries WHERE country_name = 'France')),
('Under Canvas Mount Rushmore',
(SELECT country_id FROM countries WHERE country_name = 'United States')),
('Riggs Washington D.C.',
(SELECT country_id FROM countries WHERE country_name = 'United States')),
('Waldorf Astoria Los Cabos Pedregal',
(SELECT country_id FROM countries WHERE country_name = 'Mexico')),
('The Oberoi Vanyavilas Wildlife Resort',
(SELECT country_id FROM countries WHERE country_name = 'India')),
('Canaves Oia Epitome ',
(SELECT country_id FROM countries WHERE country_name = 'Greece')),
('The Standard ',
(SELECT country_id FROM countries WHERE country_name = 'Thailand')),
('The Oberoi Amarvilas',
(SELECT country_id FROM countries WHERE country_name = 'India')),
('Hotel Santa Caterina',
(SELECT country_id FROM countries WHERE country_name = 'Italy')),
('Raffles Grand Hotel d''Angkor',
(SELECT country_id FROM countries WHERE country_name = 'Cambodia')),
('Nihi Sumba',
(SELECT country_id FROM countries WHERE country_name = 'Indonesia')),
('La R�serve Paris',
(SELECT country_id FROM countries WHERE country_name = 'France')),
('Hotel de la Ville',
(SELECT country_id FROM countries WHERE country_name = 'Italy')),
('Il San Pietro di Positano',
(SELECT country_id FROM countries WHERE country_name = 'Italy')),
('Six Senses Yao Noi',
(SELECT country_id FROM countries WHERE country_name = 'Thailand')),
('Finca Cortesin Hotel Golf & Spa',
(SELECT country_id FROM countries WHERE country_name = 'Spain')),
('Secret Bay',
(SELECT country_id FROM countries WHERE country_name = 'Dominica')),
('Cape Grace',
(SELECT country_id FROM countries WHERE country_name = 'South Africa')),
('Taj Lake Palace',
(SELECT country_id FROM countries WHERE country_name = 'India')),
('Taj Falaknuma Palace',
(SELECT country_id FROM countries WHERE country_name = 'India')),
('Alila Villas Uluwatu',
(SELECT country_id FROM countries WHERE country_name = 'Indonesia')),
('Manoir Hovey',
(SELECT country_id FROM countries WHERE country_name = 'Canada')),
('Six Senses Con Dao',
(SELECT country_id FROM countries WHERE country_name = 'Vietnam')),
('Cavas Wine Lodge',
(SELECT country_id FROM countries WHERE country_name = 'Argentina')),
('Grand Hotel Tremezzo',
(SELECT country_id FROM countries WHERE country_name = 'Italy')),
('Nayara Springs',
(SELECT country_id FROM countries WHERE country_name = 'Costa Rica')),
('Lodge on Little St. Simons Island',
(SELECT country_id FROM countries WHERE country_name = 'United States')),
('Rancho Santana',
(SELECT country_id FROM countries WHERE country_name = 'Nicaragua')),
('Amanpuri',
(SELECT country_id FROM countries WHERE country_name = 'Thailand')),
('Mandarin Oriental Marrakech',
(SELECT country_id FROM countries WHERE country_name = 'Morocco')),
('Namale Resort & Spa',
(SELECT country_id FROM countries WHERE country_name = 'Fiji')),
('Gibb''s Farm',
(SELECT country_id FROM countries WHERE country_name = 'Tanzania')),
('Jade Mountain',
(SELECT country_id FROM countries WHERE country_name = 'St. Lucia')),
('Borgo Egnazia',
(SELECT country_id FROM countries WHERE country_name = 'Italy')),
('Four Seasons Hotel Kyoto',
(SELECT country_id FROM countries WHERE country_name = 'Japan')),
('San Ysidro Ranch',
(SELECT country_id FROM countries WHERE country_name = 'United States')),
('The Goring',
(SELECT country_id FROM countries WHERE country_name = 'England')),
('The Oberoi Rajvilas',
(SELECT country_id FROM countries WHERE country_name = 'India')),
('Palm Island Resort',
(SELECT country_id FROM countries WHERE country_name =
'Saint Vincent and the Grenadines')),
('Hotel Savoy',
(SELECT country_id FROM countries WHERE country_name = 'Italy')),
('Rambagh Palace',
(SELECT country_id FROM countries WHERE country_name = 'India')),
('Curtain Bluff',
(SELECT country_id FROM countries WHERE country_name = 'Antigua')),
('Morrison House Old Town Alexandria, Autograph Collection',
(SELECT country_id FROM countries WHERE country_name = 'United States')),
('The Lytle Park Hotel,Autograph Collection',
(SELECT country_id FROM countries WHERE country_name = 'United States')),
('Twin Farms',
(SELECT country_id FROM countries WHERE country_name = 'United States')),
('Deer Path Inn',
(SELECT country_id FROM countries WHERE country_name = 'United States')),
('One&Only Nyungwe House',
(SELECT country_id FROM countries WHERE country_name = 'Rwanda')),
('W Santiago',
(SELECT country_id FROM countries WHERE country_name = 'Chile')),
('Shangri-La Singapore',
(SELECT country_id FROM countries WHERE country_name = 'Singapore')),
('L''Ermitage Beverly Hills',
(SELECT country_id FROM countries WHERE country_name = 'United States')),
('Silo Hotel',
(SELECT country_id FROM countries WHERE country_name = 'South Africa')),
('Katikies Santorini',
(SELECT country_id FROM countries WHERE country_name = 'Greece')),
('Nobu Hotel',
(SELECT country_id FROM countries WHERE country_name = 'United States')),
('The Shore Club',
(SELECT country_id FROM countries WHERE country_name =
'Turks and Caicos Islands')),
('Taj Holiday Village Resort & Spa',
(SELECT country_id FROM countries WHERE country_name = 'India')),
('Mandarin Oriental Bangkok',
(SELECT country_id FROM countries WHERE country_name = 'Thailand')),
('Auberge Saint-Antoine',
(SELECT country_id FROM countries WHERE country_name = 'Canada')),
('Rosewood Miramar Beach',
(SELECT country_id FROM countries WHERE country_name = 'United States')),
('Rio Celeste Hideaway Hotel',
(SELECT country_id FROM countries WHERE country_name = 'Costa Rica')),
('Hotel Caesar Augustus',
(SELECT country_id FROM countries WHERE country_name = 'Italy')),
('Grand Hotel Villa Serbelloni',
(SELECT country_id FROM countries WHERE country_name = 'Italy')),
('Le Bristol Paris',
(SELECT country_id FROM countries WHERE country_name = 'France')),
('Shangri-La Bosphorus',
(SELECT country_id FROM countries WHERE country_name = 'Turkey')),
('The Palms Turks & Caicos',
(SELECT country_id FROM countries WHERE country_name =
'Turks and Caicos Islands')),
('The Lodge at Blue Sky,Auberge Resorts Collection',
(SELECT country_id FROM countries WHERE country_name = 'United States')),
('Little Palm Island Resort & Spa',
(SELECT country_id FROM countries WHERE country_name = 'United States')),
('Le Sirenuse',
(SELECT country_id FROM countries WHERE country_name = 'Italy')),
('andBeyond Ngorongoro Crater Lodge',
(SELECT country_id FROM countries WHERE country_name = 'Tanzania')),
('Casa San Agust�n',
(SELECT country_id FROM countries WHERE country_name = 'Colombia')),
('The Connaught',
(SELECT country_id FROM countries WHERE country_name = 'England')),
('Wentworth Mansion',
(SELECT country_id FROM countries WHERE country_name = 'United States')),
('Taj Lands End',
(SELECT country_id FROM countries WHERE country_name = 'India')),
('Birkenhead House',
(SELECT country_id FROM countries WHERE country_name = 'South Africa'));
"""
